### PR TITLE
Changes from main Repo

### PR DESCRIPTION
**Pull request by Saphareas**
Hey, I implemented all changes from the main repository scince your fork. Maybe then the localization gets merged.

### CODE REVIEW

**Comment by gervasiocaj** [comment]
If this get merged with @TristanBomb repo, won't it erase the commit history?

**Comment by Saphareas** [comment]
Fck, the only thing I didn't think through -.- Should I correct this issue or are you already on it?

**Comment by gervasiocaj** [comment]
I'm working on it, thanks for the effort :bowing_man:

**Comment by Saphareas** [comment]
Corrected it in my repo anyways, not nice, but it works.

**Pull request closed without merging**
